import { sql, type Db } from "../db.ts";

export interface BudgetLimits { per_minute: number; per_hour: number; per_day: number }
export type WorkloadClass = "recent" | "background";
export interface RequestReservePolicy { enabled: boolean; perHour: number; perDay: number; tracking: boolean }
export interface ReserveBudget {
  reserved: { minute: number; hour: number; day: number };
  backgroundCaps: { minute: number; hour: number; day: number };
  remainingBackground: { minute: number; hour: number; day: number };
  blockedWindow: "hour" | "day" | null;
  retryAt: Date | null;
  recentHours: 48;
}
export interface ServiceBudget {
  available: boolean;
  blockedWindow: "minute" | "hour" | "day" | "stopped" | null;
  retryAt: Date | null;
  remaining: { minute: number; hour: number; day: number } | null;
  blockedReason?: "budget" | "background-reserve" | null;
  reserve?: ReserveBudget;
}

// These tags are generated by analyze.ts for ordinary steps. An admin run prefixes them with its
// own attempt tag; matching the exact purpose/tag pair keeps explicit re-evaluations background.
const AUTOMATIC_TAGS: Record<string, Array<string | undefined>> = {
  prefilter_article: [undefined], score_article: ["score-1", "score-2"],
  understand_article: ["understand"], summarize_article: ["summarize"], structure_article: ["structure"],
};
const nonnegativeInt = (value: unknown, fallback: number) => Number.isSafeInteger(value) && (value as number) >= 0 ? value as number : fallback;

/** Missing migration/config keeps the previous budget behavior; disabling reserve still tracks new attempts. */
export async function readRequestReserve(db: Db = sql): Promise<RequestReservePolicy> {
  const [row] = await db<{ value: Record<string, unknown> | null; tracking: boolean }[]>`SELECT
    (SELECT value FROM settings WHERE key = 'processing.request-reserve') AS value,
    EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid = 'receipt_attempts'::regclass AND attname = 'workload_class' AND NOT attisdropped) AS tracking`;
  return { enabled: row!.tracking && row!.value?.enabled === true, tracking: row!.tracking,
    perHour: nonnegativeInt(row!.value?.perHour, 40), perDay: nonnegativeInt(row!.value?.perDay, 200) };
}

/** Classification is checked under the paid-request service lock and recorded per attempt, never inferred later. */
export async function classifyRequestWorkload(req: { purpose: string; subject?: string | null; attemptTag?: string }, db: Db = sql): Promise<WorkloadClass> {
  if (!AUTOMATIC_TAGS[req.purpose]?.includes(req.attemptTag)) return "background";
  const match = /^article:([a-zA-Z0-9_-]{1,120})@([1-9][0-9]*)$/.exec(req.subject ?? "");
  if (!match || !Number.isSafeInteger(Number(match[2]))) return "background";
  const [row] = await db`SELECT a.id FROM articles a JOIN sources s ON s.id = a.source_id
    WHERE a.id = ${match[1]} AND a.revision = ${Number(match[2])} AND s.participation_mode = 'editorial'
      AND a.published_at >= now() - interval '48 hours' AND a.published_at <= now()`;
  return row ? "recent" : "background";
}

/** Advisory scheduling only. paidRequest still checks under its service lock before sending. */
export function budgetSnapshot(limits: BudgetLimits | undefined, attempts: Date[], now: Date): ServiceBudget {
  if (!limits) return { available: true, blockedWindow: null, retryAt: null, remaining: null };
  const windows = [
    { key: "minute" as const, ms: 60_000, cap: limits.per_minute },
    { key: "hour" as const, ms: 3_600_000, cap: limits.per_hour },
    { key: "day" as const, ms: 86_400_000, cap: limits.per_day },
  ];
  const remaining = { minute: 0, hour: 0, day: 0 };
  let blockedWindow: ServiceBudget["blockedWindow"] = null, retry = 0;
  for (const window of windows) {
    const recent = attempts.map(a => a.getTime()).filter(t => t > now.getTime() - window.ms).sort((a,b) => a-b);
    remaining[window.key] = Math.max(0, window.cap - recent.length);
    if (window.cap <= 0) { blockedWindow = "stopped"; continue; }
    if (recent.length >= window.cap && blockedWindow !== "stopped") {
      blockedWindow ??= window.key;
      // Drop enough oldest attempts to make count strictly less than the cap.
      retry = Math.max(retry, recent[recent.length - window.cap]! + window.ms);
    }
  }
  return { available: blockedWindow === null, blockedWindow, remaining,
    retryAt: blockedWindow && blockedWindow !== "stopped" ? new Date(retry + 1000) : null };
}

/** Reserves are part of each existing cap; small services retain at least half their cap for background work. */
export function applyRequestReserve(base: ServiceBudget, limits: BudgetLimits | undefined, backgroundAttempts: Date[], now: Date,
  policy: RequestReservePolicy, workload: WorkloadClass = "background"): ServiceBudget {
  if (!limits || !policy.enabled) return base;
  const reserved = { minute: 0, hour: Math.min(policy.perHour, Math.max(0, Math.floor(limits.per_hour / 2))), day: Math.min(policy.perDay, Math.max(0, Math.floor(limits.per_day / 2))) };
  const backgroundCaps = { minute: limits.per_minute, hour: limits.per_hour - reserved.hour, day: limits.per_day - reserved.day };
  const remainingBackground = { minute: 0, hour: 0, day: 0 };
  let blockedWindow: ReserveBudget["blockedWindow"] = null, retry = 0;
  for (const window of [{ key: "minute" as const, ms: 60_000 }, { key: "hour" as const, ms: 3600_000 }, { key: "day" as const, ms: 86400_000 }]) {
    const times = backgroundAttempts.map(a => a.getTime()).filter(t => t > now.getTime() - window.ms).sort((a, b) => a - b);
    const cap = backgroundCaps[window.key];
    remainingBackground[window.key] = Math.min(base.remaining?.[window.key] ?? 0, Math.max(0, cap - times.length));
    // Minute has no reservation; stopped or exhausted total caps are already described by base.
    if (window.key !== "minute" && reserved[window.key] > 0 && cap > 0 && times.length >= cap) {
      blockedWindow ??= window.key;
      retry = Math.max(retry, times[times.length - cap]! + window.ms);
    }
  }
  const reserve: ReserveBudget = { reserved, backgroundCaps, remainingBackground, blockedWindow, retryAt: blockedWindow ? new Date(retry + 1000) : null, recentHours: 48 };
  const blocked = base.available && workload === "background" && blockedWindow !== null;
  return { ...base, reserve, blockedReason: base.available ? blocked ? "background-reserve" : null : "budget",
    ...(blocked ? { available: false, blockedWindow, retryAt: reserve.retryAt } : {}) };
}

export async function readServiceBudget(service: string, db: Db = sql, workload: WorkloadClass = "background", policy?: RequestReservePolicy): Promise<ServiceBudget> {
  const [limits] = await db<BudgetLimits[]>`SELECT per_minute,per_hour,per_day FROM budgets WHERE service=${service}`;
  if (!limits) return budgetSnapshot(undefined, [], new Date());
  const [clock] = await db<{ now: Date }[]>`SELECT now() AS now`;
  // Row JSON also works before 0046, where the new column does not exist yet.
  const attempts = await db<{ started_at: Date; workload_class: WorkloadClass }[]>`SELECT started_at, coalesce(to_jsonb(a)->>'workload_class', 'background') AS workload_class FROM receipt_attempts a
    WHERE service=${service} AND origin='live' AND started_at > ${new Date(clock!.now.getTime()-86_400_000)}`;
  const base = budgetSnapshot(limits, attempts.map(a => a.started_at), clock!.now);
  return applyRequestReserve(base, limits, attempts.filter(a => a.workload_class !== "recent").map(a => a.started_at), clock!.now, policy ?? await readRequestReserve(db), workload);
}
